import React from 'react'



function Terms() {
  return (
    <section className='flex box-border	items-center flex-col bg-black h-screen'>
      <div className='flex justify-center flex-col w-[343px] lg:w[512px] mt-10 font-medium'>
        <h1 className='text-[#FFFFFFEB] text-xl text-center mb-4'>Reel Talk Terms of Service</h1>
      </div>
      <div className='flex flex-col justify-center items-center w-[343px] h-[542px] lg:w-[512px] pt-6 px-4 rounded-lg bg-gray-500'>
        <p className='overflow-y-auto no-scrollbar text-sm font-normal text-[#FFFFFFEB]'> Last Updated: October 22, 2023 <br />       Welcome, and thank you for your interest in Reel Talk, Llc. (“<span className='font-semibold'>Reel Talk</span>,” “<span className='font-semibold'>we</span>,” or “<span className='font-semibold'>us</span>”) and our website at www.Reel Talk.io, along with our related websites, networks, applications, mobile applications, and other services provided by us (collectively, the “Service”). These Terms of Service are a legally binding contract between you (event if you are using the Services on behalf of a company) and Reel Talk regarding your use of the Service. <br />

          <span className='font-semibold'>PLEASE READ THE FOLLOWING TERMS CAREFULLY.</span> <br />

          <span className='font-semibold'>BY CLICKING “SIGNUP” OR OTHERWISE ACCESSING OR USING THE SERVICE</span>, YOU AGREE THAT YOU HAVE READ AND UNDERSTOOD, AND, AS A CONDITION TO YOUR USE OF THE SERVICE, YOU AGREE TO BE BOUND BY, THE FOLLOWING TERMS AND CONDITIONS, INCLUDING REEL TALK’S PRIVACY POLICY (TOGETHER, THESE “TERMS”). If you are not eligible, or do not agree to the Terms, then you do not have our permission to use the Service. YOUR USE OF THE SERVICE, AND REEL TALK’S PROVISION OF THE SERVICE TO YOU, CONSTITUTES AN AGREEMENT BY REEL TALK AND BY YOU TO BE BOUND BY THESE TERMS.

          Arbitration NOTICE. Except for certain kinds of disputes described in Section 16, you agree that disputes arising under these Terms will be resolved by binding, individual arbitration, and BY ACCEPTING THESE TERMS, YOU AND REEL TALK ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN ANY CLASS ACTION OR REPRESENTATIVE PROCEEDING. YOU AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under this contract (except for matters that may be taken to small claims court). Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury. (See Section 16.)

          1. Reel Talk Service Overview.
          Reel Talk is a marketplace that facilitates dating relationships and connections by connecting users based on mutual preferences and interests and other information provided by the user.

          2. Eligibility.
          By agreeing to these Terms, you represent and warrant to us that you have not previously been suspended or removed from the Service and that your registration and your use of the Service is in compliance with any and all applicable laws and regulations. If you are a user, you represent and warrant to us that you are at least 18 years old. If you are a Company, the individual accepting these Terms on your behalf represents and warrants that they have authority to bind you to these Terms and you agree to be bound by these Terms.

          3. Accounts and Registration.
          To access most features of the Service, you must register for an account. When you register for an account, you may be required to provide us with some information about yourself, such as your name, email address, or other contact information. You agree that the information you provide to us is accurate and that you will keep it accurate and up-to-date at all times. When you register, you will be asked to provide a password. You are solely responsible for maintaining the confidentiality of your account and password, and you accept responsibility for all activities that occur under your account. If you believe that your account is no longer secure, then you must immediately notify us at reelworldapp@gmail.com.

          4. Payment.
          Certain features of the Service may require you to pay fees for each month or year that the Service is provided to you (such periods of time, your “Subscription”). Before you pay any fees, you will have an opportunity to review and accept the fees that you will be charged. All fees are in U.S. dollars and are non-refundable.

          4.1 Price. Reel Talk reserves the right to determine pricing for the Service, including whether to offer the Service free of charge. Reel Talk may change the fees for any feature of the Service, including additional fees or charges, if Reel Talk gives you advance notice of changes before they apply. Reel Talk, at its sole discretion, may make promotional offers with different features and different pricing to any of Reel Talk’s customers. These promotional offers, unless made to you, will not apply to your offer or these Terms.

          4.2 Annual Subscriptions. If you subscribe annually to the Service, we will renew your annual Subscription until you notify us that you do not wish to renew your annual Subscription by cancelling your subscription via the app or site.

          4.3 Monthly Subscriptions. If you subscribe to the Service on a monthly basis, we will bill your credit or debit account each month for the applicable fees as set forth in this section. We will continue billing your credit or debit account each month until you notify us that you wish to cancel your monthly Subscription by cancelling your subscription via the app or site.

          4.4 Authorization. As a monthly subscriber, you authorize Reel Talk to charge all sums for your Subscription each month, including all applicable taxes, to the payment method specified in your account.
          a. Recurring Charges. Monthly Subscriptions include automatically recurring monthly payments (“Recurring Charges”). As a monthly subscriber, you authorize Reel Talk to periodically charge, on a going-forward basis and until cancellation of your monthly Subscription, all accrued sums on or before the payment due date for the accrued sums. The “Recurring Charge Billing Date” is the date when you purchase your first Subscription to the Service. Your account will be charged automatically on the Recurring Charge Billing Date each month all applicable fees and taxes for the next monthly Subscription period. The Subscription will continue unless and until you cancel your monthly Subscription or your payment account, or your subscription is otherwise terminated as set forth herein. You must cancel your Subscription before it renews in order to avoid billing of the next periodic Recurring Charge to your account. We will bill the periodic Recurring Charge to the payment method you provide to us during registration (or to a different payment method if you change your payment information).

          4.5 Delinquent Accounts. Reel Talk may suspend or terminate access to the Service, including fee-based portions of the Service, for any account for which any amount is due but unpaid. In addition to the amount due for the Service, a delinquent account will be charged with fees or charges that are incidental to any chargeback or collection of any the unpaid amount, including collection fees.

          5. Licenses
          5.1 Limited License for Users. If you are a user, subject to your complete and ongoing compliance with these Terms, Reel Talk grants you, solely for your personal, non-commercial use, a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to: (a) install and use one object code copy of any mobile application associated with the Service obtained from a legitimate marketplace on a mobile device that you own or control; and (b) access and use the Service.

          5.2 Limited License for Companies. If you are a Company, subject to your complete and ongoing compliance with these Terms, Reel Talk grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to: (a) install and use object code copies of any mobile application associated with the Service obtained from a legitimate marketplace on mobile devices that you own or control; and (b) access and use the Service.

          5.3 License Restrictions. Except and solely to the extent such a restriction is impermissible under applicable law, you may not: (a) reproduce, distribute, publicly display, or publicly perform the Service; (b) make modifications to the Service; or (c) interfere with or circumvent any feature of the Service, including any security or access control mechanism. If you are prohibited under applicable law from using the Service, you may not use it.

          5.4 Feedback. If you choose to provide input and suggestions regarding problems with or proposed modifications or improvements to the Service (“Feedback”), then you hereby grant Reel Talk an unrestricted, perpetual, irrevocable, non-exclusive, fully-paid, royalty-free right to exploit the Feedback in any manner and for any purpose, including to improve the Service and create other products and services.

          6. Ownership
          Proprietary Rights. The Service is owned and operated by Reel Talk. The visual interfaces, graphics, design, compilation, information, data, computer code (including source code or object code), products, software, services, and all other elements of the Service (“Materials”) provided by Reel Talk are protected by intellectual property and other laws. All Materials included in the Service are the property of Reel Talk or its third party licensors. Except as expressly authorized by Reel Talk, you may not make use of the Materials. Reel Talk reserves all rights to the Materials not granted expressly in these Terms.

          7. Third Party Terms
          7.1 Third Party Services and Linked Websites. Reel Talk may provide tools through the Service that enable you to export information, including User Content (as defined below), to third party services, including through features that allow you to link your account on Reel Talk with an account on the third party service, such as Twitter or Facebook, or through our implementation of third party buttons (such as “like” or “share” buttons). By using one of these tools, you agree that Reel Talk may transfer that information to the applicable third party service. Third party services are not under Reel Talk’s control, and, to the fullest extent permitted by law, Reel Talk is not responsible for any third party service’s use of your exported information. The Service may also contain links to third party websites. Linked websites are not under Reel Talk’s control, and Reel Talk is not responsible for their content.

          7.2 Third Party Software. The Service may include or incorporate third party software components that are generally available free of charge under licenses granting recipients broad rights to copy, modify, and distribute those components (“Third Party Components”). Although the Service is provided to you subject to these Terms, nothing in these Terms prevents, restricts, or is intended to prevent or restrict you from obtaining Third Party Components under the applicable third party licenses or to limit your use of Third Party Components under those third party licenses.

          8. User Content
          8.1 User Content Generally. Certain features of the Service may permit Companies and Candidates (collectively, “Users”) to upload content to the Service, including messages, reviews, photos, video, images, folders, data, text, resumes, and other types of works (“User Content”) and to publish User Content on the Service. You retain any copyright and other proprietary rights that you may hold in the User Content that you post to the Service.

          8.2 Limited License Grant to Reel Talk for User Content. By providing User Content to or via the Service, you grant Reel Talk a worldwide, non-exclusive, irrevocable, royalty-free, fully paid right and license (with the right to sublicense) to host, store, transfer, display, perform, reproduce, modify for the purpose of formatting for display, and distribute your User Content, in whole or in part, in any media formats and through any media channels now known or hereafter developed.

          8.3 Limited License Grant to Other Users. By providing User Content to or via the Service to other Users, such as when a Candidate provides their resume to a Company on the Service, you grant those Users a non-exclusive license to access and use that User Content as permitted by these Terms and the functionality of the Service.

          8.4 User Content Representations and Warranties. Reel Talk disclaims any and all liability in connection with User Content. You are solely responsible for your User Content and the consequences of providing User Content via the Service. By providing User Content via the Service, you affirm, represent, and warrant that:

          a. you are the creator and owner of the User Content, or have the necessary licenses, rights, consents, and permissions to authorize Reel Talk and Users to use and distribute your User Content as necessary to exercise the licenses granted by you in this Section, in the manner contemplated by Reel Talk, the Service, and these Terms;

          b. your User Content, and the use of your User Content as contemplated by these Terms, does not and will not: (i) infringe, violate, or misappropriate any third party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; or (iii) cause Reel Talk to violate any law or regulation; and

          c. your User Content could not be deemed by a reasonable person to be objectionable, profane, indecent, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate.

          8.5 User Content & User Disclaimer. We are under no obligation to edit or control User Content that you or other Users post or publish, and will not be in any way responsible or liable for User Content. Reel Talk may, however, at any time and without prior notice, screen, remove, edit, or block any User Content that in our sole judgment violates these Terms or is otherwise objectionable. You understand that when using the Service you will be exposed to User Content from a variety of sources and acknowledge that User Content may be inaccurate, offensive, indecent, or objectionable. You agree to waive, and do waive, any legal or equitable right or remedy you have or may have against Reel Talk with respect to User Content. If notified by a User or content owner that User Content allegedly does not conform to these Terms, we may investigate the allegation and determine in our sole discretion whether to remove the User Content, which we reserve the right to do at any time and without notice. For clarity, Reel Talk does not permit copyright-infringing activities on the Service. Reel Talk, upon discovering via thorough investigation that a user violated the community policy guidelines, may ban a user entirely from the platform.

          8.6 Monitoring Content. Reel Talk does not control and does not have any obligation to monitor: (a) User Content; (b) any content made available by third parties; or (c) the use of the Service by its Users. You acknowledge and agree that Reel Talk reserves the right to, and may from time to time, monitor any and all information transmitted or received through the Service for operational and other purposes. If at any time Reel Talk chooses to monitor the content, Reel Talk still assumes no responsibility or liability for content or any loss or damage incurred as a result of the use of content. During monitoring, information may be examined, recorded, copied, and used in accordance with our Privacy Policy.

          9. Prohibited Conduct.
          BY USING THE SERVICE YOU AGREE NOT TO:

          a. use the Service for any illegal purpose or in violation of any local, state, national, or international law;

          b. harass, threaten, demean, embarrass, or otherwise harm any other User ;

          c. violate, or encourage others to violate, any right of a third party, including by infringing or misappropriating any third party intellectual property right;

          d. interfere with security-related features of the Service, including by: (i) disabling or circumventing features that prevent or limit use or copying of any content; or (ii) reverse engineering or otherwise attempting to discover the source code of any portion of the Service except to the extent that the activity is expressly permitted by applicable law;

          e. interfere with the operation of the Service or any User’s enjoyment of the Service, including by: (i) uploading or otherwise disseminating any virus, adware, spyware, worm, or other malicious code; (ii) making any unsolicited offer or advertisement to another User; (iii) collecting personal information about another User or third party without consent; or (iv) interfering with or disrupting any network, equipment, or server connected to or used to provide the Service;

          f. perform any fraudulent activity including impersonating any person or entity, claiming a false affiliation, accessing any other Service account without permission;

          g. sell or otherwise transfer the access granted under these Terms or any Materials (as defined in Section 6) or any right or ability to view, access, or use any Materials; or

          h. attempt to do any of the acts described in this Section 9 or assist or permit any person in engaging in any of the acts described in this Section 9.

          10. Digital Millennium Copyright Act
          10.1 DMCA Notification. We comply with the provisions of the Digital Millennium Copyright Act applicable to Internet service providers (17 U.S.C. §512, as amended). If you have an intellectual property rights-related complaint about material posted on the Service, you may contact our Designated Agent at the following address:
          Reel Talk, Inc. ATTN: Legal Department (Copyright Notification) 6548 Bradley Place, Los Angeles, CA 90056 Email: reelworldapp@gmail.com
          Any notice alleging that materials hosted by or distributed through the Service infringe intellectual property rights must include the following information:

          a. an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other right being infringed;

          b. a description of the copyrighted work or other intellectual property that you claim has been infringed;

          c. a description of the material that you claim is infringing and where it is located on the Service;

          d. your address, telephone number, and email address;

          e. a statement by you that you have a good faith belief that the use of the materials on the Service of which you are complaining is not authorized by the copyright owner, its agent, or the law; and

          f. a statement by you that the above information in your notice is accurate and that, under penalty of perjury, you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner’s behalf.

          10.2 Repeat Infringers. Reel Talk will promptly terminate the accounts of Users that are determined by Reel Talk to be repeat infringers.

          11. Modification of these Terms.
          We reserve the right to change these Terms on a going-forward basis at any time. Please check these Terms periodically for changes. If a change to these Terms materially modifies your rights or obligations, we may require that you accept the modified Terms in order to continue to use the Service. Material modifications are effective upon your acceptance of the modified Terms. Immaterial modifications are effective upon publication. Disputes arising under these Terms will be resolved in accordance with the version of these Terms that was in effect at the time the dispute arose.

          12. Term, Termination and Modification of the Service

          12.1 Term. These Terms are effective beginning when you accept the Terms or first download, install, access, or use the Service, and ending when terminated as described in Section 12.2.

          12.2 Termination. If you violate any provision of these Terms, your authorization to access the Service and these Terms automatically terminates. Reel Talk may, at its sole discretion, terminate these Terms or your account on the Service, or suspend or terminate your access to the Service, at any time for any reason or no reason, with or without notice. You may terminate these Terms at any time; provided that, if you are a Company with a paid Subscription, such termination will not be effective until the end of your current Subscription period.

          12.3 Effect of Termination. Upon termination of these Terms: (a) your license rights will terminate and you must immediately cease all use of the Service; (b) you will no longer be authorized to access your account or the Service; and (c) the following obligations will survive such termination: any obligation accrued prior to such termination to pay money to the other party, and the obligations set forth in Sections 5.4, 6, 8.2, 8.3, 12.3, and 13 through 17.

          12.4 Modification of the Service. Reel Talk reserves the right to modify or discontinue the Service at any time (including by limiting or discontinuing certain features of the Service), temporarily or permanently. Reel Talk will have no liability for any change to the Service or any suspension or termination of your access to or use of the Service, except a pro-rated refund of any Subscription fees you have paid for the period following such discontinuation or termination.

          13. Indemnity.
          To the fullest extent permitted by law, you are responsible for your use of the Service, and you will defend and indemnify Reel Talk and its officers, directors, employees, consultants, affiliates, subsidiaries and agents (together, the “Reel Talk Entities”) from and against every claim brought by a third party, and any related liability, damage, loss, and expense, including reasonable attorneys’ fees and costs, arising out of or connected with: (a) your unauthorized use of, or misuse of, the Service; (b) your violation of any portion of these Terms, any representation, warranty, or agreement referenced in these Terms, or any applicable law or regulation; (c) your violation of any third party right, including any intellectual property right or publicity, confidentiality, other property, or privacy right; or (d) any dispute or issue between you and any third party, including (if you are a Company) claims related to your hiring practices or hiring decisions, such as claims brought by job applicants or potential job applicants. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (without limiting your indemnification obligations with respect to that matter) and in that case, you agree to cooperate with our defense of those claims.

          14. Disclaimers; No Warranties
          THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE ARE PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS. REEL TALK DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, RELATING TO THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE, INCLUDING: (A) ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT; AND (B) ANY WARRANTY ARISING OUT OF COURSE OF DEALING, USAGE, OR TRADE. REEL TALK DOES NOT WARRANT THAT THE SERVICE OR ANY PORTION OF THE SERVICE, OR ANY MATERIALS OR CONTENT OFFERED THROUGH THE SERVICE, WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS, AND REEL TALK DOES NOT WARRANT THAT ANY OF THOSE ISSUES WILL BE CORRECTED.

          NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE SERVICE OR REEL TALK ENTITIES OR ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE SERVICE WILL CREATE ANY WARRANTY REGARDING ANY OF THE REEL TALK ENTITIES OR THE SERVICE THAT IS NOT EXPRESSLY STATED IN THESE TERMS. WE ARE NOT RESPONSIBLE FOR ANY DAMAGE THAT MAY RESULT FROM THE SERVICE AND YOUR DEALING WITH ANY OTHER SERVICE USER. YOU UNDERSTAND AND AGREE THAT YOU USE ANY PORTION OF THE SERVICE AT YOUR OWN DISCRETION AND RISK, AND THAT WE ARE NOT RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM OR MOBILE DEVICE USED IN CONNECTION WITH THE SERVICE) OR ANY LOSS OF DATA, INCLUDING USER CONTENT.

          REEL TALK DOES NOT CONDUCT BACKGROUND CHECKS. REEL TALK DOES NOT WARRANT THAT CANDIDATES WILL OBTAIN JOBS OR THAT CANDIDATES WILL BE TRUTHFUL, QUALIFIED OR SATISFACTORY.
          REEL TALK doES not make ANY hiring decisions, AND r Companies REMAIN SOLELY RESPONSIBLE FOR THE DECISION TO HIRE (OR NOT TO HIRE) PARTICULAR CANDIDATES.

          THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS IN THIS SECTION APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. Reel Talk does not disclaim any warranty or other right that Reel Talk is prohibited from disclaiming under applicable law.

          15. Limitation of Liability
          TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL THE REEL TALK ENTITIES BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, OR ANY OTHER INTANGIBLE LOSS) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR YOUR INABILITY TO ACCESS OR USE, THE SERVICE OR ANY MATERIALS OR CONTENT ON THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ANY REEL TALK ENTITY HAS BEEN INFORMED OF THE POSSIBILITY OF DAMAGE.

          EXCEPT AS PROVIDED IN SECTION 16.4 AND TO THE FULLEST EXTENT PERMITTED BY LAW, THE AGGREGATE LIABILITY OF THE REEL TALK ENTITIES TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE USE OF OR ANY INABILITY TO USE ANY PORTION OF THE SERVICE OR OTHERWISE UNDER THESE TERMS, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS LIMITED TO THE GREATER OF: (A) THE AMOUNT YOU HAVE PAID TO REEL TALK FOR ACCESS TO AND USE OF THE SERVICE IN THE 12 MONTHS PRIOR TO THE EVENT OR CIRCUMSTANCE GIVING RISE TO CLAIM; OR (B) $100.

          EACH PROVISION OF THESE TERMS THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS INTENDED TO AND DOES ALLOCATE THE RISKS BETWEEN THE PARTIES UNDER THESE TERMS. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF THESE TERMS. THE LIMITATIONS IN THIS SECTION 15 WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.

          16. Dispute Resolution and Arbitration
          16.1 Generally. In the interest of resolving disputes between you and Reel Talk in the most expedient and cost effective manner, and except as described in Section 16.2, you and Reel Talk agree that every dispute arising in connection with these Terms will be resolved by binding arbitration. Arbitration is less formal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. This agreement to arbitrate disputes includes all claims arising out of or relating to any aspect of these Terms, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of these Terms. YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND REEL TALK ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.

          16.2 Exceptions. Despite the provisions of Section 16.1, nothing in these Terms will be deemed to waive, preclude, or otherwise limit the right of either party to: (a) bring an individual action in small claims court; (b) pursue an enforcement action through the applicable federal, state, or local agency if that action is available; (c) seek injunctive relief in a court of law in aid of arbitration; or (d) to file suit in a court of law to address an intellectual property infringement claim.

          16.3 Arbitrator. Any arbitration between you and Reel Talk will be settled under the Federal Arbitration Act and administered by the American Arbitration Association (“AAA”) under its Consumer Arbitration Rules (collectively, “AAA Rules”) as modified by these Terms. The AAA Rules and filing forms are available online at www.adr.org, by calling the AAA at 1-800-778-7879, or by contacting Reel Talk. The arbitrator has exclusive authority to resolve any dispute relating to the interpretation, applicability, or enforceability of this binding arbitration agreement.

          16.4 Notice of Arbitration; Process. A party who intends to seek arbitration must first send a written notice of the dispute to the other party by certified U.S. Mail or by Federal Express (signature required) or, only if that other party has not provided a current physical address, then by electronic mail (“Notice of Arbitration”). Reel Talk’s address for Notice is: reelworldapp@gmail.com. The Notice of Arbitration must: (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought (“Demand”). The parties will make good faith efforts to resolve the claim directly, but if the parties do not reach an agreement to do so within 30 days after the Notice of Arbitration is received, you or Reel Talk may commence an arbitration proceeding. All arbitration proceedings between the parties will be confidential unless otherwise agreed by the parties in writing. During the arbitration, the amount of any settlement offer made by you or Reel Talk must not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any. If the arbitrator awards you an amount higher than the last written settlement amount offered by Reel Talk in settlement of the dispute prior to the award, Reel Talk will pay to you the higher of: (i) the amount awarded by the arbitrator; or (ii) $10,000.

          16.5 Fees. If you commence arbitration in accordance with these Terms, Reel Talk will reimburse you for your payment of the filing fee, unless your claim is for more than $10,000, in which case the payment of any fees will be decided by the AAA Rules. Any arbitration hearing will take place at a location to be agreed upon in San Francisco, California, but if the claim is for $10,000 or less, you may choose whether the arbitration will be conducted: (a) solely on the basis of documents submitted to the arbitrator; (b) through a non-appearance based telephone hearing; or (c) by an in-person hearing as established by the AAA Rules in the county (or parish) of your billing address. If the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules. In that case, you agree to reimburse Reel Talk for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator must issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within 14 days of the arbitrator’s ruling on the merits.

          16.6 No Class Actions. YOU AND REEL TALK AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and Reel Talk agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding.

          16.7 Modifications to this Arbitration Provision. If Reel Talk makes any future change to this arbitration provision, other than a change to Reel Talk’s address for Notice of Arbitration, you may reject the change by sending us written notice within 30 days of the change to Reel Talk’s address for Notice of Arbitration, in which case your account with Reel Talk will be immediately terminated and this arbitration provision, as in effect immediately prior to the changes you rejected will survive.

          16.8 Enforceability. If Section 16.6 is found to be unenforceable or if the entirety of this Section 16 is found to be unenforceable, then the entirety of this Section 16 will be null and void and, in that case, the parties agree that the exclusive jurisdiction and venue described in Section 17.2 will govern any action arising out of or related to these Terms.

          17. Miscellaneous
          17.1 General Terms. These Terms, together with the Privacy Policy and any other agreements expressly incorporated by reference into these Terms, are the entire and exclusive understanding and agreement between you and Reel Talk regarding your use of the Service. You may not assign or transfer these Terms or your rights under these Terms, in whole or in part, by operation of law or otherwise, without our prior written consent. We may assign these Terms at any time without notice or consent. The failure to require performance of any provision will not affect our right to require performance at any other time after that, nor will a waiver by us of any breach or default of these Terms, or any provision of these Terms, be a waiver of any subsequent breach or default or a waiver of the provision itself. Use of section headers in these Terms is for convenience only and will not have any impact on the interpretation of any provision. Throughout these Terms the use of the word “including” means “including but not limited to”. If any part of these Terms is held to be invalid or unenforceable, the unenforceable part will be given effect to the greatest extent possible, and the remaining parts will remain in full force and effect.

          17.2 Governing Law. These Terms are governed by the laws of the State of California without regard to conflict of law principles. You and Reel Talk submit to the personal and exclusive jurisdiction of the state courts and federal courts located within San Francisco, California for resolution of any lawsuit or court proceeding permitted under these Terms. We operate the Service from our offices in California, and we make no representation that Materials included in the Service are appropriate or available for use in other locations.

          17.3 Privacy Policy. Please read the Reel Talk Privacy Policy (available at www.reelworld.co/privacy) carefully for information relating to our collection, use, storage, disclosure of your personal information. The Reel Talk Privacy Policy is incorporated by this reference into, and made a part of, these Terms.

          17.4 Additional Terms. Your use of the Service is subject to all additional terms, policies, rules, or guidelines applicable to the Service or certain features of the Service that we may post on or link to from the Service (the “Additional Terms”). All Additional Terms are incorporated by this reference into, and made a part of, these Terms.

          17.5 Consent to Electronic Communications. By using the Service, you consent to receiving certain electronic communications from us as further described in our Privacy Policy. Please read our Privacy Policy to learn more about our electronic communications practices. You agree that any notices, agreements, disclosures, or other communications that we send to you electronically will satisfy any legal communication requirements, including that those communications be in writing.

          17.6 Contact Information. The Service is offered by Reel Talk, Inc. You may contact us by emailing us at reelworldapp@gmail.com.

          17.7 Notice to California Residents. If you are a California resident, under California Civil Code Section 1789.3, you may contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 N. Market Blvd., Suite S-202, Sacramento, California 95834, or by telephone at (800) 952-5210 in order to resolve a complaint regarding the Service or to receive further information regarding use of the Service.

          17.8 No Support. We are under no obligation to provide support for the Service. In instances where we may offer support, the support will be subject to published policies.

          17.9 International Use. The Service is intended for visitors located within the United States. We make no representation that the Service is appropriate or available for use outside of the United States. Access to the Service from countries or territories or by individuals where such access is illegal is prohibited.

          18. Notice Regarding Apple.
          This Section 18 only applies to the extent you are using our mobile application on an iOS device. You acknowledge that these Terms are between you and Reel Talk only, not with Apple Inc. (“Apple”), and Apple is not responsible for the Service or the content thereof. Apple has no obligation to furnish any maintenance and support services with respect to the Service. If the Service fails to conform to any applicable warranty, you may notify Apple and Apple will refund any applicable purchase price for the mobile application to you; and, to the maximum extent permitted by applicable law, Apple has no other warranty obligation with respect to the Service. Apple is not responsible for addressing any claims by you or any third party relating to the Service or your possession and/or use of the Service, including: (a) product liability claims; (b) any claim that the Service fails to conform to any applicable legal or regulatory requirement; or (c) claims arising under consumer protection or similar legislation. Apple is not responsible for the investigation, defense, settlement and discharge of any third party claim that the Service and/or your possession and use of the Service infringe a third party’s intellectual property rights. You agree to comply with any applicable third party terms when using the Service. Apple and Apple’s subsidiaries are third party beneficiaries of these Terms, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary of these Terms. You hereby represent and warrant that: (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.</p>
      </div>
    </section>
  )
}

export default Terms